# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PromotionApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PromotionApp

pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'

  target 'PromotionApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PromotionAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PromotionApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PromotionApp-tvOS



end
